name: Micah Crump
favicon: null
layout_spectrum: 0.94016
typography_spectrum: 0.27226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1014'
    - '#ffffff'
    - '#604633'
    - '#d8d7d7'
    - '#808081'
  brandStrength: 0.3941753916442394
  lightness: 0.6248737538699061
  saturation: 0.2254823341500014
  rhythmicContrast: 0.35429647169075906
purpose: []
